<a href="https://colab.research.google.com/github/Elwing-Chou/tibame0910/blob/main/tibame20260924_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import json
import urllib.request as req

url = "https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=38250&geo=TW%2CHK"
f = req.urlopen(url)
content = f.read()
# loads: bytes型態->list/dict型態(JSON格式)
content = json.loads(content)
# print(type(content))
# [但木{}, 但木{}...]
danmus = content["data"]["danmu"]
for d in danmus:
    print(d["userid"], d["text"])

- 標準格式
    - JSON格式: list+dict
    - CSV格式(Comma-Separtated Values)
        - 姓名,身高
        - Elwing,175
        - "Elwing, Mr. Chou",180

In [ ]:
import json
import urllib.request as req
import pandas as pd

url = "https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=38250&geo=TW%2CHK"
f = req.urlopen(url)
content = f.read()
content = json.loads(content)
danmus = content["data"]["danmu"]
# pandas: DataFrame表格型態
df = pd.DataFrame(danmus)
df.to_csv("danmu.csv", encoding="utf-8", index=False)
df.to_excel("danmu.xlsx")
df

In [14]:
data = [
    {"name":"Elwing", "height":175},
    {"name":"Elwing, Mr. Chou", "height":180}
]
pd.DataFrame(data)

               name  height
0            Elwing     175
1  Elwing, Mr. Chou     180

- pandas兩大操作
    - 過濾: 準備一個跟你資料筆數一樣多的True(留下)/False(刪除)
    - 轉換: 準備一個函式, 參數就是原始資料, return轉換的東西

In [17]:
# demo: 過濾
fil = [True, False, True]
df.head(3)[fil]

  text    color  size  position  time        sn       userid
0    1  #FFFFFF     1         0     0  39929764   andy475713
2  簽🌭️  #FDE53D     1         0     0  40273436  shackle9487

In [20]:
s = "andy475713"
fil = df["userid"] == s
df[fil]

  text    color  size  position  time        sn      userid
0    1  #FFFFFF     1         0     0  39929764  andy475713

In [ ]:
# demo
def func(n):
    return n + 100
df["time"].apply(func)

In [24]:
def func(s):
    s = s.replace("#", "")
    r, g, b = s[:2], s[2:4], s[4:]
    r, g, b = int(r, 16), int(g, 16), int(b, 16)
    return (r, g, b)
df["color"].apply(func)

0       (255, 255, 255)
1       (255, 255, 255)
2        (253, 229, 61)
3        (253, 229, 61)
4       (255, 255, 255)
             ...
2996    (255, 255, 255)
2997    (255, 148, 150)
2998     (181, 56, 250)
2999       (255, 0, 38)
3000    (255, 255, 255)
Name: color, Length: 3001, dtype: object